version: '2.1'
services:

  postgres:
    container_name: postgres
    restart: unless-stopped
    image: postgres:13-alpine
    environment: 
      - POSTGRES_PASSWORD=password
    ports: 
      - 5432:5432
  
  connect_du:
    build: 
      context: ./
      dockerfile: ./Dockerfile
    restart: unless-stopped
    container_name: connect_du
    environment: 
      - DATABASE_URL=postgres://postgres:password@postgres:5432/connect_du
      - SECRET=secret
    ports: 
      - 80:80
    depends_on: 
      - postgres