name: server
description: An empty Aqueduct application.
version: 1.0.0
author: PoloLacoste

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  aqueduct: 3.3.0+1
  common:
    path: ../common
  crypto: ^2.1.5
  dart_jsonwebtoken: ^1.5.1

dev_dependencies:
  test: ^1.0.0
  aqueduct_test: ^1.0.0

dependency_overrides:
  postgres: ^2.2.0